[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "unofficial-elm-guide"
authors = [{name = "Gautam Bisht", email = "gbisht@pnnl.gov"}]
dynamic = ["version", "description"]

